### PR TITLE
Added P2P tunnel part for OpenComputers.

### PR DESCRIPTION
**Pull request by fnuecke**
As discussed with @FireBall1725 on IRC, here's a PR adding a P2P tunnel part for OpenComputers networking.

Tested with and without OC, in dev-env and normal MC via vanilla launcher.

One thing that needs specific review are the adjusted enums. I believe the ones where I did not append the entry to the end to be order irrelevant, but verification of that is needed.

### CODE REVIEW

**Comment by thatsIch** [comment]
we would pull this into rv3 now, 
not sure if anything particular new was added on your side.

Else I can do the rabase on it.

**Comment by fnuecke** [comment]
Great! I'll update it to the current state of the rv2 branch and check if it's still working.

**Comment by thatsIch** [comment]
rebase it against the master (this will be the future rv3)

**Comment by fnuecke** [comment]
Oops, messed that up. Will make a new PR against master.

**Comment by thatsIch** [comment]
welcome to github :D

**Comment by fnuecke** [comment]
Haha, yeah. I pretty much expected that to horribly fail, admittedly :P

**Pull request closed without merging**
