### PR TITLE
Draft: Fabric 21w08b

### PR DESCRIPTION
**Pull request by petabyteboy**
Spatial storage is probably heavily broken (search the code for FIXME 1.17), but everything else should work fine

You might need to build [LibBlockAttributes](https://github.com/petabyteboy/LibBlockAttributes/tree/0.8.x-1.17.x) and [RoughlyEnoughItems](https://github.com/petabyteboy/RoughlyEnoughItems) and `publishToMavenLocal`.

### CODE REVIEW

**Comment by petabyteboy** [comment]
The meteorite compass doesn't work in some cases (multiplayer?).

**Comment by shartte** [comment]
@petabyteboy Thanks a lot for your work, but you should probably hold off.
We just learned Forge will be moving to official Mojang mappings for 1.17 (including class names), and we will switch ASAP to fully use mojang mappings too, for both Forge and Fabric. This will make syncing both versions MASSIVELY easier.

**Comment by Technici4n** [comment]
I also don't think there are plans to merge this PR before 1.17 pre-releases or even RCs start rolling, as it would mean having to port patches between 3 branches instead of 2.

**Comment by yueh** [comment]
Closing due for the current idea of moving fabric to mcp or both branches to official mappings if possible. As well as first trying to synchronize both to an ideally equal state.

**Pull request closed without merging**
