### PR TITLE
Better 'dimension ID taken' error message

### PR DESCRIPTION
**Pull request by Pingger**
Now includes the Name of the Dimension, which took our ID.
Should help resolving errors like these more easily: #4189

### CODE REVIEW

**Comment by yueh** [comment]
I'd recommend contributing this to forge. It cannot be our job to fix their broken shit.

They could easily use identifieres to register new dimensions similar to everything else like blocks, recipes and so on. Which works perfectly fine and hasn't caused id conflicts since probably forever.

**Comment by ksx-kshan** [comment]
That's true, however, in the interim this would be a friendly way to help users resolve conflicts. Given that the dimension registration will need updated if Forge implements dimension registry anyway, I would have recommended merging this change.

**Comment by yueh** [comment]
If people cannot read "dimension [Number] already registered", they certainly won't read "dimension is taken by [Mod]"

**Comment by ksx-kshan** [comment]
That's definitely a valid point. I yield.

Even knowing which mod is conflicting doesn't help that much because you can easily just change the AE config to use some random higher number and it will most likely then succeed.

**Comment by Pingger** [comment]
Yes, but at the moment we can't point people to the mod, that IS causing the issues. While I will try to get this added to forge, at the moment it isn't and I don't really have the time work on an additional project.
And while people don't read, that the dimension ID is already taken, with this change we can at least point them in the right direction to fixing the issue.

Also: YAY **yueh** is back! Welcome back after your break!

**Comment by Ommina** [comment]
With the change away from integer dimension IDs for 14.0 and above, is it even worth worrying about at this point?

**Comment by yueh** [comment]
Both mods are causing it. There isn't really someone to blame besides maybe the modpack author throwing a pack together without understanding it.

We simply decided to postpone the dimension registration to a later event phase (I think it was also the recommended one for it). So in cases some other mod uses the same id, we can actually break instead of forcing it to load and corrupt the dimensions.

But we could certainly have choosen a better starting id. E.g. some random number, but it's simply too late for this now.

And still, this should be forge notifying the user about which addons are clashing. In case some other mod uses the same approach, but crashes earlier, the users still won't have a clue about it, except this mod also has a custom error reporting.

**Pull request closed without merging**
