### PR TITLE
Allow extraction for Condenser

### LINKED ISSUE #2017: Storage bus unable to view items in matter condenser
If a storage bus is connected to a matter condenser with matter balls or singularities in it, they will not be visible in a terminal. Hoppers/import busses/item conduits/etc… are all capable of extracting items from the condenser, and the storage bus is capable of inserting items, but not extracting them. Changing the input/output mode does not make a difference, nor does enabling "report inaccessible items" (this won't show the storage component in the condenser either, though that's less of a concern). The storage bus DOES seem to work normally on other modded inventories, just not the condenser. Using rv2-stable-10.

Oh, and clicking the partition storage button doesn't do anything either; matter balls/singularities do not get added to the filter.

### LINKED ISSUE #2602: Items cannot be extracted from Matter Condenser
Exactly as the title said, i tried lots of diferent ways of extraction from this block, but nothing works

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-5
- Forge Version: 12.18.2.2122

### LINKED ISSUE #2960: Not able to extract from Matter Condenser
Just putting this her for the reminder. 
"Not being able to extract from the condenser is because they don't expose Item capabilities yet"

- Minecraft Version:  1.12
- AE2 Version: Custom version on ATC
- Forge Version: 2415

### PR DESCRIPTION
**Pull request by fscan**
fixes #2960, fixes #2017, fixes #2602

### CODE REVIEW

**Comment by orod-org** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [TileCondenser.java#L112](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/00b707ea8a3bc36be34deefe144c38efbe521a35/src/main/java/appeng/tile/misc/TileCondenser.java#L112): Cast one of the operands of this multiplication operation to a "double". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2184)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by orod-org** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [TileCondenser.java#L112](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/26f05b8a3f70fcaef69529ff5265ff22005c5996/src/main/java/appeng/tile/misc/TileCondenser.java#L112): Cast one of the operands of this multiplication operation to a "double". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2184)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by orod-org** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [TileCondenser.java#L112](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/a088272c18fca763dcf7887821101d8335c1bd96/src/main/java/appeng/tile/misc/TileCondenser.java#L112): Cast one of the operands of this multiplication operation to a "double". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2184)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by mindforger** [comment]
and maybe even those

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2017
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2602
maybe have a look at https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1350 too in this case to make it complete? 

and i've read something about possible balancing or default item routing issues in some of the closed ones, maybe add an testing session :)

**Comment by orod-org** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [TileCondenser.java#L112](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/ef65a7ee0bb4fad2c05316e5665e71abfe7788fc/src/main/java/appeng/tile/misc/TileCondenser.java#L112): Cast one of the operands of this multiplication operation to a "double". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS2184)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by mrossleslie** [comment]
Can this fix be pushed to 1.10, please?

**Pull request merged**
