### PR TITLE
Use craftinggrid to check existing patterns for JEI recipe transfer.

### PR DESCRIPTION
**Pull request by yueh**
It will prefer existing patterns before using the existing items as fallback.

### CODE REVIEW

**Comment by yueh** [comment]
test this please.

**Comment by yueh** [comment]
test this please.

**Comment by yueh** [comment]
test this please.

**Comment by yueh** [comment]
test this please.

**Comment by RalphPvp** [comment]
PMN IMHOo;9o

On Nov 9, 2017 7:47 AM, "yueh" <notifications@github.com> wrote:

test this please.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/3202#issuecomment-343176568>,
or mute the thread

**Pull request merged**
