### PR TITLE
don't return more than the original injected input

### PR DESCRIPTION
**Pull request by Mari023**
should fix https://github.com/TeamAOF/All-of-Fabric-5/issues/65

### CODE REVIEW

**Comment by Mari023** [comment]
interestingly, this is already accounted for in AEBaseBlockItemChargeable
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/94624c1c7cdeaaa553b70b990295cc731b392bc0/src/main/java/appeng/block/AEBaseBlockItemChargeable.java#L68

I think it would be better to adjust this fix to be more inline with that (it is technically the same, but it would be nice if it was consistent)

**Comment by Technici4n** [comment]
> I think it would be better to adjust this fix to be more inline with AEBaseBlockItemChargeable (it is technically the same, but it would be nice if the code is consistent)

Agreed. Do you want to do it?

**Comment by Mari023** [comment]
actually the bug was still in AEBaseBlockItemChargeable, I fixed it there too

**Comment by Technici4n** [comment]
Thanks!

**Pull request merged**
