### PR TITLE
Fixes #3974: Some mods needlessly break setting itemdamage directly.

### LINKED ISSUE #3974: crafting CPU and repices RE-batteries from IC2
Crafting CPU stay stuck when crafting repices containing RE-Batteries from IC2.

I come from the modpack FTB Ultimate Reloaded (version `1.4.0`). I opened [an issue on their github](https://github.com/FTBTeam/FTB-Ultimate-Reloaded/issues/165). It seems this is a known bug they can't fix on their part.

**Describe the bug :** Machines crafted with RE-Batteries such as a Generator can't be crafted with the Crafting CPU from Applied Energistics 2. The crafting CPU stay stuck with the RE-Battery shown as available. I did again the pattern several times to be sure I had the right item : each time the pattern was created with a freshly created RE-Battery. Right now it seems i'm not the only one with this [issue](https://www.reddit.com/r/feedthebeast/comments/b2dhci/cannot_get_ae2_autocrafting_to_use_rebatteries_in/).

**To Reproduce**
Use FTB Ultimate Reloaded modpack in version `1.4.0`. Make a basic AE2 setup with a molecular assembler and a crafting CPU. Make a pattern for RE-Batteries and another for the IC2 Generator. Launch a autocrafting of a Generator. The process should be stuck on the crafting of the generator.

**Expected behavior**
The Generator can be autocrafted.

**Additional context**
No crashlog. I could provide screenshots if necessary but I don't have any at the moment.

**Environment**
- Minecraft Version: 1.12.2
- FTB ultimate Reloaded : 1.4.0
- AE2 Version : (from FTB Ultimate Reloaded) rv6.stable6
- IC2 Version : (from FTB Ultimate Reloaded) 2.8.11-ex112
- Forge Version : (not sure where to check that in the modpack)

### PR DESCRIPTION
**Pull request by yueh**
Technically this could also be used to repair any item...

### CODE REVIEW

**Comment by Orygeunik** [comment]
What about merger plans? When it planned?

**Comment by Orygeunik** [comment]
@yueh  do you have plans to merge it?

**Comment by bigenergy** [comment]
This fix does not work, I checked it with IC2 wires.

**Comment by ElektroKill** [comment]
I tested it and it works with RE-Battery

**Pull request closed without merging**
