### PR TITLE
You can now automate Vibration Chambers

### PR DESCRIPTION
**Pull request by TheCricket**
When attempting to automate with a lava bucket you get the bucket stuck in there, You can now automate the system using lava.

### CODE REVIEW

**Comment by TheCricket** [comment]
:dancers:

**Comment by yueh** [comment]
I am not really convinved, that this is a good chance.

First of all it will break consistency with vanilla furnaces, which do not allow fuel to be extracted.

Secondly it will break certain builds, these might not be used that much (if at all). But there is still the chance that someone uses it. For example if someone uses storage buses to keep them stacked with fuel and wants to be able to monitor it, but not allow the network to ever pull fuel from it.

**Comment by FireBall1725** [comment]
I think if it was changed to only return true if the itemstack is an empty bucket would be fine.

**Comment by TheCricket** [comment]
Ok I can do that :)

**Comment by yueh** [comment]
Please squash the commits.

**Comment by TheCricket** [comment]
so much easier to do this https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/1633

**Comment by MyDeloreanWontStart** [comment]
Doesn't Extracells have a fluid vibration chamber?

**Comment by TheCricket** [comment]
this isn't extracells is it

**Pull request closed without merging**
