### PR TITLE
update ru_ru.json for 8.3.0+ update

### PR DESCRIPTION
**Pull request by Gregorius-MC**

### CODE REVIEW

**Comment by yueh** [comment]
Thanks. 

We might still at more translation keys until a beta release. So it might be an idea to wait for it, if you do not want to update it constantly.

**Comment by Gregorius-MC** [comment]
Well, in that case, I will take my time and release the next translation update when the stable version of the mod is released.

**Comment by Gregorius-MC** [comment]
> 
> 
> Thanks.
> 
> We might still at more translation keys until a beta release. So it might be an idea to wait for it, if you do not want to update it constantly.

Well, in that case, I will take my time and release the next translation update when the stable version of the mod is released.

**Comment by yueh** [comment]
Maybe not for the stable one, as there probably won't be a patch release just to update translations. Beta should be fine and I'll try to avoid adding new keys when possible.

**Pull request merged**
