### PR TITLE
Find free DimensionType id when set to -1

### LINKED ISSUE #3036: SpatialIO doesnt respond, crashes game on save.
It seems that SpatialIO doesnt work in r5 (which i expected). I have learned that when trying to use the system and interact with a ready-made SpatialIO system, its non-responsive. It doesnt crash the game when you trigger redstone on the io port or anything. It just does nothing. However, when you try to save and exit to main menu, you crash and below is the error log.

- Error: https://pastebin.com/VJtFmkDZ
- Minecraft Version: 1.12
- AE2 Version: rv5 alpha 2
- Forge Version: 14.21.1.2443

### PR DESCRIPTION
**Pull request by fscan**
should fix #3036

### CODE REVIEW

**Comment by orod-org** [comment]
SonarQube analysis reported 10 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Registration.java#L125](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/59d13c44d5dcacad691ed8dcdd8f693c61501132/src/main/java/appeng/core/Registration.java#L125): Add a constructor to the class. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1258)
1. ![MAJOR][MAJOR] [Registration.java#L147](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/59d13c44d5dcacad691ed8dcdd8f693c61501132/src/main/java/appeng/core/Registration.java#L147): This block of commented-out lines of code should be removed. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [Registration.java#L220](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/59d13c44d5dcacad691ed8dcdd8f693c61501132/src/main/java/appeng/core/Registration.java#L220): Remove this useless assignment to local variable "partHelper". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1854)
1. ![MAJOR][MAJOR] [Registration.java#L229](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/59d13c44d5dcacad691ed8dcdd8f693c61501132/src/main/java/appeng/core/Registration.java#L229): This block of commented-out lines of code should be removed. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [Registration.java#L326](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/59d13c44d5dcacad691ed8dcdd8f693c61501132/src/main/java/appeng/core/Registration.java#L326): This block of commented-out lines of code should be removed. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [Registration.java#L336](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/59d13c44d5dcacad691ed8dcdd8f693c61501132/src/main/java/appeng/core/Registration.java#L336): This block of commented-out lines of code should be removed. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MINOR][MINOR] [AEConfig.java#L362](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/59d13c44d5dcacad691ed8dcdd8f693c61501132/src/main/java/appeng/core/AEConfig.java#L362): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [AEConfig.java#L367](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/59d13c44d5dcacad691ed8dcdd8f693c61501132/src/main/java/appeng/core/AEConfig.java#L367): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [AEConfig.java#L372](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/59d13c44d5dcacad691ed8dcdd8f693c61501132/src/main/java/appeng/core/AEConfig.java#L372): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [Registration.java#L220](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/59d13c44d5dcacad691ed8dcdd8f693c61501132/src/main/java/appeng/core/Registration.java#L220): Remove this unused "partHelper" local variable. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1481)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by orod-org** [comment]
SonarQube analysis reported 10 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Registration.java#L125](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/865580c421960ac4ce86660458126606114e19ab/src/main/java/appeng/core/Registration.java#L125): Add a constructor to the class. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1258)
1. ![MAJOR][MAJOR] [Registration.java#L147](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/865580c421960ac4ce86660458126606114e19ab/src/main/java/appeng/core/Registration.java#L147): This block of commented-out lines of code should be removed. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [Registration.java#L221](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/865580c421960ac4ce86660458126606114e19ab/src/main/java/appeng/core/Registration.java#L221): Remove this useless assignment to local variable "partHelper". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1854)
1. ![MAJOR][MAJOR] [Registration.java#L230](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/865580c421960ac4ce86660458126606114e19ab/src/main/java/appeng/core/Registration.java#L230): This block of commented-out lines of code should be removed. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [Registration.java#L327](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/865580c421960ac4ce86660458126606114e19ab/src/main/java/appeng/core/Registration.java#L327): This block of commented-out lines of code should be removed. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [Registration.java#L337](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/865580c421960ac4ce86660458126606114e19ab/src/main/java/appeng/core/Registration.java#L337): This block of commented-out lines of code should be removed. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MINOR][MINOR] [AEConfig.java#L362](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/865580c421960ac4ce86660458126606114e19ab/src/main/java/appeng/core/AEConfig.java#L362): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [AEConfig.java#L367](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/865580c421960ac4ce86660458126606114e19ab/src/main/java/appeng/core/AEConfig.java#L367): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [AEConfig.java#L372](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/865580c421960ac4ce86660458126606114e19ab/src/main/java/appeng/core/AEConfig.java#L372): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [Registration.java#L221](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/865580c421960ac4ce86660458126606114e19ab/src/main/java/appeng/core/Registration.java#L221): Remove this unused "partHelper" local variable. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1481)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by orod-org** [comment]
SonarQube analysis reported 10 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Registration.java#L125](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/f96a6135e9adc7238fe3ae2b42819b5867381884/src/main/java/appeng/core/Registration.java#L125): Add a constructor to the class. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1258)
1. ![MAJOR][MAJOR] [Registration.java#L147](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/f96a6135e9adc7238fe3ae2b42819b5867381884/src/main/java/appeng/core/Registration.java#L147): This block of commented-out lines of code should be removed. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [Registration.java#L226](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/f96a6135e9adc7238fe3ae2b42819b5867381884/src/main/java/appeng/core/Registration.java#L226): Remove this useless assignment to local variable "partHelper". [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1854)
1. ![MAJOR][MAJOR] [Registration.java#L235](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/f96a6135e9adc7238fe3ae2b42819b5867381884/src/main/java/appeng/core/Registration.java#L235): This block of commented-out lines of code should be removed. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [Registration.java#L332](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/f96a6135e9adc7238fe3ae2b42819b5867381884/src/main/java/appeng/core/Registration.java#L332): This block of commented-out lines of code should be removed. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [Registration.java#L342](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/f96a6135e9adc7238fe3ae2b42819b5867381884/src/main/java/appeng/core/Registration.java#L342): This block of commented-out lines of code should be removed. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MINOR][MINOR] [AEConfig.java#L362](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/f96a6135e9adc7238fe3ae2b42819b5867381884/src/main/java/appeng/core/AEConfig.java#L362): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [AEConfig.java#L367](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/f96a6135e9adc7238fe3ae2b42819b5867381884/src/main/java/appeng/core/AEConfig.java#L367): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [AEConfig.java#L372](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/f96a6135e9adc7238fe3ae2b42819b5867381884/src/main/java/appeng/core/AEConfig.java#L372): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [Registration.java#L226](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/f96a6135e9adc7238fe3ae2b42819b5867381884/src/main/java/appeng/core/Registration.java#L226): Remove this unused "partHelper" local variable. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS1481)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by fscan** [comment]
replaced by #3048

**Pull request closed without merging**
