### PR TITLE
Update zh_CN.lang

### PR DESCRIPTION
**Pull request by bakaxyf**
Need help
- ```gui.tooltips.appliedenergistics2.ItemsStored=Items Stored: %s
gui.tooltips.appliedenergistics2.ItemsRequestable=Items Requestable: %s```
 
      I cant figure out where are them in game
-  What does "A" in ETA stand for?

### CODE REVIEW

**Comment by yueh** [comment]
The first strings are used in tooltips (see their keys). The `Items Stored: %s` should only appear after the icon flips to using prefixes like K or M (so over 1 or 10k items depending on our settings).

Similar for `Items Requestable: %s`, but I am not not sure if these are actually possible to view currently.
It is mostly a preparation for a logistics pipes integration. I think the only option which could show them is with autocrafting. If I remember correctly, overflow items are still stored inside the crafting cpu until done, but are requestable for other crafting jobs. For example crafting sticks from a single log will also produce 2 left over planks. If you can somehow prevent the sticks from being crafted, it might be possible that the tooltip will also show 2 requestable planks.

ETA stands for "estimated time of arrival", it is certainly not the perfect term for on based on the actual behaviour. Estimated Time To Complete (ETC) would probably be better but is less known.
But there is a good chance that this string will go away in the near future. So it might be pointless to translate it.

**Comment by bakaxyf** [comment]
Oh,thanks. I will update after test.

**Comment by thatsIch** [comment]
Depending on https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/1577

**Comment by bakaxyf** [comment]
I has tested, but I still couldn't find ``Items Requestable: %s``, Maybe there is something I did wrongly
.More detail?
I translated it literally, and will keep test. If have some mistake, I will fix in next update.

**Comment by bakaxyf** [comment]
I think can merge now.

**Comment by thatsIch** [comment]
@yueh, you are required here

**Comment by thatsIch** [comment]
You need to squash them first

**Comment by bakaxyf** [comment]
okey

**Pull request closed without merging**
