### PR TITLE
Update zh_CN.lang

### PR DESCRIPTION
**Pull request by bakaxyf**

### CODE REVIEW

**Comment by TheJulianJES** [comment]
Why do you want to change this back?

**Comment by thatsIch** [comment]
good question

**Comment by bakaxyf** [comment]
Technically speaking, "合成" (lit. compose, compound; assemble) cannot cover the meaning of "craft".
Then I need to have further discussion with my buddies.

**Comment by TheJulianJES** [comment]
Okayyyy....

**Pull request merged**
