### PR TITLE
add highlight for craftable ingredients

### PR DESCRIPTION
**Pull request by vfyjxf**
This is a port of the unmerged feature in #6493, which was rejected due to the use of the old api。
JEI:

dev(6)

REI: 

dev(7)

### CODE REVIEW

**Comment by vfyjxf** [comment]
Since I mainly want to add this feature in 1.18.2 first, please let me know if you would accept it if I implement it using the new api.

**Comment by Technici4n** [comment]
Please submit your PRs to the `master` branch when applicable (here it's applicable :P ).

I'm fine with a backport to 1.18.2 forge yeah.

**Comment by Technici4n** [comment]
Hmmm, I find the feature a bit weird though now that I actually look at the description. It's strange to highlight craftable outputs imo.

**Comment by vfyjxf** [comment]
> Hmmm, I find the feature a bit weird though now that I actually look at the description. It's strange to highlight craftable outputs imo.

Because I don't think there is any difference between output and input, and of course people are more concerned about whether the input is craftable , maybe I should make some changes?

**Comment by vfyjxf** [comment]
Well I've removed the highlight for the output.

**Comment by Technici4n** [comment]
Ah, I like that feature. However I feel like most of the implementation could perhaps be shared with the other highlight for crafting recipes. If you want I can have a shot at it.

**Comment by vfyjxf** [comment]
>  If you want I can have a shot at it.

Yes, I would like you to do that.

**Comment by vfyjxf** [comment]
You could probably also make this a bit more powerful, such as supporting gas ingredients for mek, but I noticed that ae2 does not provide a generic AEKey comparator.

**Comment by Technici4n** [comment]
Superseded by #6528, thanks for your initial work upon which I based my PR! 🙂

**Pull request closed without merging**
