### PR TITLE
Might fix #397: Now file name of meteor data is encoded correctly

### LINKED ISSUE #397: Seed "Errors" (Too many meteors)
Apparently I'm being suggested to start AE. http://puu.sh/cFfQL/d26046eccd.jpg  http://puu.sh/cFfWf/7cca9d1d8c.jpg  http://puu.sh/cFg1B/755d4707d8.jpg (I'd hate to be that guys barber)  Seed is : 113963865144355269 with BoP installed, but not enabled.

### PR DESCRIPTION
**Pull request by thatsIch**
Basically it added the integer and chars..

### CODE REVIEW

**Comment by yueh** [comment]
That can be quite an impacting change to existing worlds.

That is really something which should be covered by unittests, but `Configuration` makes it basically impossible as it will crash when not running in a fully working forge environment...

**Comment by thatsIch** [comment]
anything IO related is stupid to unit test,
could just mock it

**Comment by yueh** [comment]
Not necessarily to sucessfully create the files, but are the file names correct and similar things.

**Comment by thatsIch** [comment]
I think I will put the tests in https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/1526
cause currently the `WorldSettings` is a singleton, no much testing to be done there

**Comment by thatsIch** [comment]
Will close this in favor of #1526 

already contains the fix + outsourced encoder

**Pull request closed without merging**
