### PR TITLE
Replace raw long counting with a Long2LongMap accumulator

### PR DESCRIPTION
**Pull request by cplir-c**
Attempts to fix the [fluid using 1 Bucket = 81k items issue](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/7321).

I chose to use a Long2LongMap accumulator so that different AEKeyTypes with the same denominator could be summed in the same map slot, and avoid the internal-rounding issues that would be had if I divided all the values by their Unit denominators.

### CODE REVIEW

**Comment by 62832** [comment]
We greatly prefer PRs like these to be submitted against the `main` branch targeting the latest version and not any previous version branches.

**Comment by cplir-c** [comment]
Seems it didn't help... still getting 81k

**Comment by cplir-c** [comment]
Tested using a water bucket -> lava bucket pattern that just goes into a trashing matter condenser. I requested 2 buckets and gave it 1 lava bucket. [Image](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAWIAAAB/CAMAAADivTi5AAABhGlDQ1BJQ0MgcHJvZmlsZQAAKJF9kT1Iw0AcxV9TpSIVUTsUEclQneyiIo61CkWoEGqFVh1MLv2CJg1Jiouj4Fpw8GOx6uDirKuDqyAIfoA4OzgpukiJ/0sKLWI9OO7Hu3uPu3eAUC8zzeqKAZpum6lEXMxkV8XAKwIYxABGEZaZZcxJUhIdx9c9fHy9i/Kszuf+HH1qzmKATySOMcO0iTeIZzZtg/M+cYgVZZX4nHjCpAsSP3Jd8fiNc8FlgWeGzHRqnjhELBbaWGljVjQ14mniiKrplC9kPFY5b3HWylXWvCd/YTCnryxzneYIEljEEiSIUFBFCWXYiNKqk2IhRfvxDv5h1y+RSyFXCYwcC6hAg+z6wf/gd7dWfmrSSwrGge4Xx/kYAwK7QKPmON/HjtM4AfzPwJXe8lfqwOwn6bWWFjkC+reBi+uWpuwBlztA+MmQTdmV/DSFfB54P6NvygJDt0Dvmtdbcx+nD0CaukreAAeHwHiBstc7vLunvbd/zzT7+wGNr3KxQEZVsgAAAE5QTFRFAAAAHAQQEQoaGAkXHAweIQg8JgVbIRw9AC45KSsoNjg1Pj89UUAmXV9czUQH1FYMhW37gIJ/3XkdALfdpqilBtX/pMaVxcfE2dzZ////lPoQuQAABx5JREFUeNrtnYl6qkgQhRM1Zma4UWNmsrz/i45FWVZVL0Ajazz1XaHpRsRfPF2L5D79rNSenmj5tQJbzYlGJx6deVVb2/NkH7vs8hz/vHAciOdG/PX1GxDL22x+uzraDW68JxAD8fiIpa2iYb/k0ta1l4FwK32EdMt/yHocIAbifojjqSns0W2LpkluUtNdauq0x/nFQgHEEwhFm8t1L+L4qCmhAOI5EI/tvufecncXqovTlsLdDXFquksdob1P20A8LeLx3feSL2b/ALqLUOjr59DkLrzUR5F2ChNCAcSTIR7efQ9dqrRQpNz+7oiHsJIzKEhmAvFsiId039va4SQ1F+JR3EsgnhHxkO57F8RdXUYgBuIuiMd13/NHLnHggBiIc5m2Kdz35nR3X6H4Z7EGxFMjXqr73gXx5yLs/f07MCBeI+J5UvJADMR9bTebbbfhdrkB8W9EXOqObLf7VVsZ5MPNjsfz+Xi185nbhwMQLwXxf0W22ez3mxEsloFYHu4Xij6ICSUjFsi0ZvBAvBzEHwU2DmKCx4+UzY1YILMdjAHx2hHzLS7akraMWoS0pT1+bMmICaiHau14BOKlIa7zOLLmBvcr30sPnaZgov0YHj9H2jzOa4FKozLix5aM+Hz2iLXN018RYuVZCc0mxFsgngCxYCJ4IhQWpGLUmxMV+HqE4nAg0B6wQO6DuEko6n4VCiCeDLEKBfU0C0VqbCbEVXV51P8SVkUBtAYful043RnERhaaprt1I64syYjwXIgbr+KwvVyhqOrrl5b1g5vS03AVk2CQ9Q49HgfxpwpEva75XpefEyCuSoXCOmo5xMsSCr5q+yC2SSFe9w09LNKqMps3xJeTJUzbVSJOX8WiFwtCTJBDR80H1unQIxSNWa/iGrBev6LF1Q13nP5RxCQZE+Uo1oY450RUVT7TNhNiDqAZpP/ia7/tk72qSl28NSQzxV3jYFoct8LCEhAvAvH1xc7Pz/v9M9uDpOTFXQuLSoOn5IkvEA+C+K0BMTF+LMR+klNn7Z6qx9tbhvGxvooPByAG4oFT8mFB1IYgfRBX1dt7hvEZiIdCTIzffHwnV/Hh/HCI5YdWMWDu7SMUAePqtpBjA/G9iP8Q40AsLGJzFZ9qI0CnmzEw7Y9h/ns1bnvEOZsXMUuFFQwB3Eco/lzswtgRvgoFEE+O+HR63rxejDCeTq83Y7DSoqUHvNn8fTXaouWSEQ/0E25FTITrGS4CfA09Lh8dEN+DmAl/RDJ802LKgahQMD7CaGWCAYtgCPJQKFItQkBLaXOL2oRTBEbbK0QcAzYF/49rqH4E4v6IU4R9dFcHH9ZpY6yEkUWCRcPi5j4vFyQSglbavBa83CbjfoK623Gbt2X/tSFuzLSdrzMqEE+IWKc1MUbqcYeARS50uqMliQHjI3gMV4RC+kkYuK39fRC/T2D98sUXZ/AIxCMjvlzGx6N32ngy05CDEdt2ONm1IxYcLBmC1+MWK705cr/f7b4Ht5Fqd3J9AnEnxCX/fQmf5m6nQfPrq2ztdr4tY/ZNisPFeLwTJjj9vtIX4y6/xZfOfZL/5AWIJ0b8V5HxlEGmQbNu2RFu6VKMv+K65fv8FCaCoFAV94qEohTxywsQFyIuc0f0Kh7W2tJAKai5W3qB+PEQlx1Oprsx/qBHeTITiIH4PsTdHCdNQOqyDTG7fRaxOIj+yEAMxPch1pRiM2Dei8NjnrbaEBNcTiRZxJJcssdejdMGxItFLG9QkuYCOywAyaik1n34q1sqDByqENZYKCgkTyG2r6ofbyhnQAzEjPjlJXyDmsQR6NKWxKO0bDIyLBhZN42nO4u4XSj0mJJisukj3ofOHYiBOI1YQlufPLd76bZFYNsWME94frojKeF1XijCY4YJUSAG4hRi+9X0zlwXxBaBB8zrrojDV5Ue3w/EQOwRdysHhRhixPF0Z0tWzU5b/CMs+8FLa7VCAcQTIJY0eRwW2/S5HaG2PCRo0Q/Khh62ZMXJHulJvU6q2KSva/uBGIhDxEOYApgiJQ/EQDwG4mkLS0AMxGmnraSwlEvbK2JfVOKW/GjLIuX0Z+p4cQkKiIE4F0D3Kyyl9uGRuKgk4YcG0H6iTCHm8MSnPYEYiNuSmSWFJS8vMmYR+6KSR+wT8rkfwXJ4Yn+Uq88DYiAeorBkC0ASQitine5ixNxr5cWWqMIJj39CHgbeQAzEQxSWcgWg1HRnEftEZjotasWCxSF04IAYiIcpLOnNBSnE+emOsLcjFqBSgvIOHBAD8f2FpdQfPchNd1pgSjttOaGwN6WF5SggBuIhCkvhqLZ9WckXmBiSddo4gJZylP+5VnwEGaEb2ma4zRyIF4wYKXlUPYAYiIF4PsRrNiD+nYhLHZLtdo7bzIcRijEAA/ESEH8vwn5+8h+2nO/TE/1RmOWdOxDPgPh/T5NMnr4xM7QAAAAASUVORK5CYII=)

**Comment by cplir-c** [comment]
I'll try some more tomorrow.
Would it be ok for me to get it working first and then import the changes to 1.20.4 and 1.21?

**Comment by cplir-c** [comment]
I'd change this to a draft PR if I could

**Comment by Technici4n** [comment]
I would do it using floating point numbers.

**Comment by Simba98** [comment]
> I would do it using floating point numbers.

Alternatively, we may scale up the item type by AEFluidType.getAmountPerUnit()
And then on GUI scale down.
This can keep it int type, and more importantly, as financial programmers usually do, using int type will keep computing precise.

**Pull request closed without merging**
