### PR TITLE
Remove coremod completely and leftover integration handling to FML

### PR DESCRIPTION
**Pull request by Prototik**
So as @yueh asking - removed coremod completely as everything that AE needs already implemented in FML.

### CODE REVIEW

**Comment by orod-org** [comment]
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [ClientHelper.java#L84](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/dbffc3b070ddc95dc3b93c9f6ba6429539c86ce0/src/main/java/appeng/client/ClientHelper.java#L84): Method appeng.client.ClientHelper.preinit() orders expressions in a conditional in a sub optimal way [rule](https://sonar.orod.org/coding_rules#rule_key=fb-contrib%3ASEO_SUBOPTIMAL_EXPRESSION_ORDER)
1. MINOR [AppEng.java#L255](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/dbffc3b070ddc95dc3b93c9f6ba6429539c86ce0/src/main/java/appeng/core/AppEng.java#L255): Remove this use of "instance"; it is deprecated. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. MINOR [AppEng.java#L261](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/dbffc3b070ddc95dc3b93c9f6ba6429539c86ce0/src/main/java/appeng/core/AppEng.java#L261): Remove this use of "instance"; it is deprecated. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)

**Comment by yueh** [comment]
We cannot use `@Optional` as it fails with generics as well as not supporting to be disabled by a config option.

**Comment by Prototik** [comment]
@yueh please stop closing PRs without any discussion.
So if you have any edits/marks/something - just type it, I could fix it.

About generics - this is fixed by stripRefs = true.
About configs - I'll take a look.

**Comment by TheMrCaveman** [comment]
So what is happening right now? This closing of PR's and issues without any comment is kinda rude.

**Pull request closed without merging**
