### PR TITLE
Changed things in de_DE.lang

### PR DESCRIPTION
**Pull request by TheJulianJES**
If the review is accepted I will also create a PR for rv2 if wanted.

### CODE REVIEW

**Comment by plumpudding** [comment]
Naja über das mit "Fluixkristall" oder "Fluix-Kristall" kann man sich streiten..

**Comment by TheJulianJES** [comment]
@plumpudding Why? It's name as item is "Fluix-Kristall" and I just changed other "Fluixkristall" to "Fluix-Kristall".

**Comment by yueh** [comment]
The - in "Fluix-Kristall" is also called "Deppenbindestrich".

"Kristall" as translation for seed is also pretty wrong.

**Comment by TheJulianJES** [comment]
Woops, the 2. is a derp.

**Comment by TheJulianJES** [comment]
Also @yueh do you think I did something wrong with the "Deppenbindestricen"?

**Comment by plumpudding** [comment]
So 4 Germans here ^^
actually if you look at http://www.deppenbindestrich.de/ it explains pretty much why I wouldn't do what you did. Additionally it is inconsistent because the other words are not seperated. 

Fazit: "Das kannste schon so machen aber dann isses halt kacke!"
Nicht zu ernst nehmen wie gesagt kann man schon so machen und ist Ansichtssache.

**Comment by TheJulianJES** [comment]
@plumpudding I would also prefeer to leave the "-" out but if you take a look at http://de.wikipedia.org/wiki/Viertelgeviertstrich#Bindestrich I think it's okay.

**Comment by thatsIch** [comment]
I also would prefer `Fluixkristall`,
you also call it Quarzkristalle for example

**Comment by TheJulianJES** [comment]
@thatsIch Yeah, so should I change all things to that?

**Comment by thatsIch** [comment]
All things?

**Comment by plumpudding** [comment]
No only change back "Fluix-Kristall" to "Fluixkristall"
As both versions are ok and most people like the version without seperation it would be a logic decision to change it back.

**Comment by TheJulianJES** [comment]
@plumpudding But it is also called "Certusquarzkristall" and not "Certusquarz-Kristall"

**Comment by plumpudding** [comment]
You seem to think the wrong way: You changed it from "Fluixkristall" (the better one) to "Fluix-Kristall".

**Comment by TheJulianJES** [comment]
@plumpudding Yeah because the normal item was called "Fluix-Kristall" and other things were just called "Fluixkristall" but I like "Fluixkristall" more than "Fluix-Kristall".

**Comment by plumpudding** [comment]
You still don't understand. You removed "Fluix-Kristall" and added "Fluixkristall" instead.

**Comment by TheJulianJES** [comment]
@plumpudding I know..

**Comment by plumpudding** [comment]
Now I'm beginning to mix them up too. xD

**Comment by TheJulianJES** [comment]
@plumpudding Can happen sometimes ;)

**Comment by TheJulianJES** [comment]
So to make it clear again:
The current name for normal Fluix Crystal is "Fluix-Kristall"
for normal Certus Quartz it is currently "Certusquarz".
So I changed all things with "Fluixkristall" to "Fluix-Kristall" so it is like the current item name.
But I would prefer "Fluixkristall" and even would change it to that if you all ok with that.

**Comment by plumpudding** [comment]
Ok now I got it. Change it all.

**Comment by TheJulianJES** [comment]
Change it all to "Fluixkristall"? @plumpudding

**Comment by plumpudding** [comment]
Yes.

**Comment by TheJulianJES** [comment]
Woops, not done :P

**Comment by thatsIch** [comment]
Could you re-add the last `\n`? Else there might be issues when people are reading the files on different OS

**Comment by TheJulianJES** [comment]
@thatsIch For me there actually is an empty line 450 but GitHub isn't recognizing it..

**Comment by TheJulianJES** [comment]
Nvm was on the wrong fork :P

**Comment by TheJulianJES** [comment]
Another question @thatsIch should I also PR this to rv2 or is it not necessary?

**Comment by thatsIch** [comment]
please do

**Pull request merged**
