### PR TITLE
Fixes #1061 Recipes are properly registered with new Mekanism

### LINKED ISSUE #1061: Mekanism 8 integration issue
Dear AppliedEnergistics team,

I'm here to inform you for an issue with AE2 (rv2.beta build 14) and Mekanism. The issue is in combination with NEI, because the Client starts up and the world loads normally, but If I try to get recipe-information from any Item or Block in the list it crashes. I posted already in Mekanism the issue https://github.com/aidancbrady/Mekanism/issues/2280#event-260998774.
But it seems to be an integration issue with the newest Mekanism API. (http://pastebin.com/xZimU9XS)

I hope I did it right,

access_denied

### PR DESCRIPTION
**Pull request by thatsIch**
Switched from API call to IMC message since it is deprecated

### CODE REVIEW

**Comment by KamranMackey** [comment]
Awesome! :)

**Comment by thatsIch** [comment]
mekcrusher= ae2:BlockSkyStone:0 -> ae2:ItemMaterial.SkyDust
    mekcrusher= mc:ender_pearl -> ae2:ItemMaterial.EnderDust
    mekcrusher= ae2:ItemMaterial.CertusQuartzCrystalCharged -> ae2:ItemMaterial.CertusQuartzDust

not working for some reason... needs investigation

**Comment by halvors** [comment]
If possible please merge this as soon as possible :)

**Comment by thatsIch** [comment]
As you may read, whole integration is not working. 
I might disable the specific named recipes for now and file a new issue regarding that to be fixed.

**Comment by halvors** [comment]
@thatsIch I know. But the mekanism crusher recipies is minor. In general not being able to craft any AE2 items is the actual issue here.

**Comment by thatsIch** [comment]
Commented out the special lines with `#bug` to indicate, that these need to be reviewed at some later time. Fixing the integration comes first.

**Comment by halvors** [comment]
@thatsIch When are this going to be merged? Whould be really nice if you could pull this an push a release :+1:

**Pull request merged**
