### PR TITLE
Issuing A Crafting Job From A Non-Native Terminal

### PR DESCRIPTION
**Pull request by Nividica**
Related to issue #683

Ensures the cancel button is never null.
Adds code to close GUI if OriginalGui is null.

### CODE REVIEW

**Comment by Nividica** [comment]
I simplified the changes as much as possible, as best I can tell the changes will only take effect when the GUI is called from a non-native AE part.

**Comment by Cisien** [comment]
Looks good, though I have a few questions.

1. what I the use case for not passing the parent GUI into this method? AE uses this to return the user to the terminal GUI that the request was created with

**Comment by yueh** [comment]
It is mostly a quick'n'dirty hack to not crash any addon terminal which is using the crafting GUI.
But to really fix it, we would have to refactor how we handle GUIs and provide a way to map tileentities back to GUIs dynamically and not static like now.

Compared to going back a step it will just close every gui instead of crashing.

**Comment by Nividica** [comment]
Indeed. The issue I am facing is that ITerminalHost that is passed into the constructor does not matching the existing checks. That is to say I am not launching the Crafting GUI from an AE GUI/Terminal, but from my own GUI/Terminal. The proposed changes prevent a crash that occurs because of that, and instead close the GUI on conformation or cancellation.

**Comment by thatsIch** [comment]
So, what about this PR?

**Comment by Nividica** [comment]
I would be very appreciative if this PR was accepted ^.^

**Comment by thatsIch** [comment]
Well, squash first, I guess?

**Pull request closed without merging**
