### PR TITLE
Ore Dictionary support for recipes

### PR DESCRIPTION
**Pull request by Adaptivity**
- Converted everything to use Ore Dictionary
- Registered chests and crafting tables in Ore Dictionary for better compatibility with ganymedes01's [WoodStuff mod](https://github.com/ganymedes01/WoodStuff)

Let me know if you want to change something.

### CODE REVIEW

**Comment by thatsIch** [comment]
TODO: I need to double check if every not specified oredict entry is already provided by Forge

**Comment by yueh** [comment]
Another question would also be, if it causes any issues when we register the crafting table/chest as oredict entry. There is probably a reason why forge does not do it already.

**Comment by Adaptivity** [comment]
@thatsIch all entries except chests and crafting tables are provided by Forge.
@yueh it doesn't causes any issues. Forge 1.8 already registered chests in Ore Dictionary. 1.7.10 lacks of support you know, Lex won't support Forge for multiple MC versions. So, modders should go ahead and do everything themselves. About 10 mods already registered chests and crafting tables without any issues including Buildcraft, Ender IO, Forestry, Ars Magica 2, OpenBlocks, StorageDrawers, Tinkers Construct, Railcraft and many others. If you have any other questions, please ask. I'll rebase my PR to solve conflicts if you say it's ready to go.

**Comment by thatsIch** [comment]
Branch has conflicts, looks fine though

**Comment by Adaptivity** [comment]
Closing as I have no time to update this. Feel free to apply these changes yourself or I might recreate this in future.

**Pull request closed without merging**
