### PR TITLE
Added feature request #817

### PR DESCRIPTION
**Pull request by Eearslya**
Crafting CPU GUI now shows a yellow background on items being crafted, and a yellow background on scheduled items.

### CODE REVIEW

**Comment by yueh** [comment]
We should probably consider adding a config option for it.
It flickers quite fast with fully upgraded assemblers and might be a bit irritating for some.

**Comment by TheJulianJES** [comment]
@yueh I would like a config option ;)

**Comment by Bestadd** [comment]
@yueh the company brig to turn it off is great but could there also be an option to change to color for those that are color blind?

**Comment by yueh** [comment]
I already considered making it configurable as a color blind option. But I do not know of a green - yellow one, so we mostly need to target a total color blindness. (Also one reason, why I suggest these two colors)

Which then needs to deal with a lot more than just the two colors, we would also have to make the font color an option as there might be not enough contrast between the (very) dark gray font color and a potentially darker gray background color.

So it would be really nice to hear, if it is an actual issue for these persons.

**Pull request merged**
