### PR TITLE
Added P2P tunnel part for OpenComputers.

### PR DESCRIPTION
**Pull request by fnuecke**
See #579.

Fixed the PR, now against master, also some small improvements (e.g. made it use the dynamic tick handling instead of rescheduling to check for connections each time it failed, so that should be nicer).

Re-tested and looking good.

### CODE REVIEW

**Comment by thatsIch** [comment]
So far looks good, I am testing it tomorrow,
you doing quick work! :D

**Comment by yueh** [comment]
`GridFlags.COMPRESSED_CHANNEL` might not be necessary. Except you want to prevent them from being tunneled through another network. But besides ME no other tunnel has this limitation.

**Comment by fnuecke** [comment]
> GridFlags.COMPRESSED_CHANNEL

Ah, right. I oriented myself on the ME tunnel for the `IGridTickable` implementation and copied that over for testing, forgot to remove it again. Removed it.

**Comment by fnuecke** [comment]
Also, if you test with OC the way I did (computer on one end, screen on the other), in particular that it keeps working after exiting and re-entering the world, make sure to [use the latest OC dev build](http://ci.cil.li/job/OpenComputers-dev-MC1.7.10/)'s OpenOS. Depending on the time it takes for things to initialize on chunk load, there was a scenario where GPUs could forget about their screens, but the screens could be back before the computer resumed for the first time, leading to the OS assuming the GPU was still aware of its screen, where it really wasn't. Fixed that in OpenOS now. So this implementation turned out to be a really good test case for that behavior!

**Comment by thatsIch** [comment]
Tested it, working fine for me,
send you a PR which you can merge,
this includes some style fixes and other random crap, the commit message should help

**Comment by fnuecke** [comment]
Merged, thanks for the cleanup!

**Comment by thatsIch** [comment]
just `rebase -i` them out. I think thats just nicer and faster than somebody bossing around to fix this and that

**Comment by fnuecke** [comment]
Sure thing, done!

**Comment by thatsIch** [comment]
Thank you for your contribution!

**Pull request merged**
