### PR TITLE
Logistics Pipes integration

### LINKED ISSUE #21: Logistics Pipes Integration
Was in AE1.

Originally Posted by AlgorithmX2

This issue was migrated; For original details see http://ae-mod.info/Tracker/0192/

### PR DESCRIPTION
**Pull request by secondfry**
Add Logistics Pipes API to Gradle
Copy BuildCraft implementation
Request API implemented
Own implementation of IRequestAPI.getProvidedItems for deduplication

Closes #21

### CODE REVIEW

**Comment by secondfry** [comment]
ATM Travis build fails due to usage of old Gradle and some certificate shenanigans from Logistics Pipes side.
`> hostname in certificate didn't match: <ci.rs485.network> != <rs485.network> OR <rs485.network>`

**Comment by Drethic** [comment]
I did a check of the xml file Travis is trying to pull down and it's not listed on the page:
```https://ci.rs485.network/job/LogisticsPipes-0.9-mc17-bc7/128/artifact/build/libs/```
The specific xml is ```ivy-0.9.3.128.xml```

Could be worth changing over to the Maven repository to see of that works:
```http://ci.rs485.network/plugin/repository/project/LogisticsPipes-0.9-mc17-bc7/```

**Comment by secondfry** [comment]
Gradle file is completely fine, there shouldn't be ivy XML if artifact
pattern specified.
Maven repository won't work, it has no artifacts inside.

**Comment by yueh** [comment]
Sorry, but we no longer support 1.7.10 actively. Which especially means not adding new features to it.

Once Logistics Pipes is available for 1.10, we will consider adding support for it. (or whatever version is the current one at that time)

**Comment by bogdantanasuca** [comment]
We can get maybe an unofficial version of ae with the lp integration fixed?

**Comment by secondfry** [comment]
Closed is closed, guys. Only thing I can try to do is release addon mod, but that would require some time.

**Comment by Telokis** [comment]
@secondfry Why do the AE2 team decides to no longer support older versions?
One little thing that I'd like to have available (as an addon) is a way to see AE2 crafts from my LP network (and vice-versa) that would be absolutely awesome.
If there is a way, I'd even pay you for it. (Paypal donation?)
What do you think?

**Comment by secondfry** [comment]
@Telokis, necroing this thread again, sorry for such delay. I had no time to develop a proper addon mod and I don't see if I'll have any time in future. I'll notice (probably here) if anything changes.

**Pull request closed without merging**
