### PR TITLE
fabric updates

### PR DESCRIPTION
**Pull request by petabyteboy**
This ports a lot of changes and fixes to the fabric/master branch and updates to the latest yarn 1.16.5 mappings, and Fabric API.

### CODE REVIEW

**Comment by shartte** [comment]
Thanks for putting in the effort!
Will review / test, which'll likely take a while

**Comment by Fogrits** [comment]
**The only issue I got after compiling it to test is this**
image

**and this**
image

**Comment by Fogrits** [comment]
it's probably some block/item tag assigning issues...

**Comment by Fogrits** [comment]
a LOT of them.

**Comment by shartte** [comment]
Help testing this is greatly appreciated.

The tags should be part of the AE2 resources however. Are they not?

**Comment by petabyteboy** [comment]
I can't reproduce it. My runtime log does not contain these messages when running from this branch. If you could describe exactly what you did to get those errors that would be helpful! :heart:

**Comment by shartte** [comment]
@Fogrits Did you run the datagen? You need to run the gradle data gen stuff before continuing.

**Comment by Fogrits** [comment]
> @Fogrits Did you run the datagen? You need to run the gradle data gen stuff before continuing.

My build failed near the end, but the main jar did compile successfully

**Comment by petabyteboy** [comment]
As it clearly tells you, you are missing a build dependency: nodejs+npm.
I think the datagen tasks runs after spotless checks and updates the jar file.

**Comment by petabyteboy** [comment]
You can also download the artifacts from an automated CI job here:

https://github.com/petabyteboy/Applied-Energistics-2/suites/1923581586/artifacts/37883312

**Comment by Fogrits** [comment]
Can Certus Quartz and Charged Certus ores only dropping XP be a consequence of not building the mod properly??

**Comment by shartte** [comment]
Yes. Loot tables are data. Generated data.

**Review by shartte — APPROVED** [review]

**Comment by shartte** [comment]
Thanks alot again, and sorry for the long delay in reviewing it.

**Pull request merged**
