### PR TITLE
Using a unified number converter to display short versions of numbers

### PR DESCRIPTION
**Pull request by thatsIch**

### CODE REVIEW

**Comment by thatsIch** [comment]
Should handle negative numbers

**Comment by thatsIch** [comment]
Now handles negative numbers and is a singleton

**Comment by thatsIch** [comment]
No, empty chars (zero length) do not exist.

**Comment by yueh** [comment]
Just to make a note about it, the old postfixes were K, M and B. Probably for millions and billions. Now these are normal metric prefixes. So instead of displaying `2B` it is now `2G`.

**Comment by thatsIch** [comment]
We could make it actually a config option

**Comment by yueh** [comment]
There is an issue with Crafting patterns, it will overlay a number over the normal text indicating it is craftable.

**Pull request merged**
