### PR TITLE
Fix Inscriber and Molecular Assembler

### PR DESCRIPTION
**Pull request by fscan**
Fix some bugs introduced in the rewrite.

### CODE REVIEW

**Comment by orod-org** [comment]
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [TileInscriber.java#L135](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/554f3686c995cd80eed0b2139ea38def219eef46/src/main/java/appeng/tile/misc/TileInscriber.java#L135): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [TileInscriber.java#L145](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/554f3686c995cd80eed0b2139ea38def219eef46/src/main/java/appeng/tile/misc/TileInscriber.java#L145): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [TileInscriber.java#L155](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/554f3686c995cd80eed0b2139ea38def219eef46/src/main/java/appeng/tile/misc/TileInscriber.java#L155): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [TileInscriber.java#L184](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/554f3686c995cd80eed0b2139ea38def219eef46/src/main/java/appeng/tile/misc/TileInscriber.java#L184): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by orod-org** [comment]
SonarQube analysis reported 8 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [TileMolecularAssembler.java#L202](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/11f74873f3a2c9ab19daaee3cf6ede3c7ba8f1d2/src/main/java/appeng/tile/crafting/TileMolecularAssembler.java#L202): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [TileMolecularAssembler.java#L210](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/11f74873f3a2c9ab19daaee3cf6ede3c7ba8f1d2/src/main/java/appeng/tile/crafting/TileMolecularAssembler.java#L210): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [TileMolecularAssembler.java#L216](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/11f74873f3a2c9ab19daaee3cf6ede3c7ba8f1d2/src/main/java/appeng/tile/crafting/TileMolecularAssembler.java#L216): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [TileMolecularAssembler.java#L237](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/11f74873f3a2c9ab19daaee3cf6ede3c7ba8f1d2/src/main/java/appeng/tile/crafting/TileMolecularAssembler.java#L237): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [TileInscriber.java#L135](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/11f74873f3a2c9ab19daaee3cf6ede3c7ba8f1d2/src/main/java/appeng/tile/misc/TileInscriber.java#L135): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [TileInscriber.java#L145](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/11f74873f3a2c9ab19daaee3cf6ede3c7ba8f1d2/src/main/java/appeng/tile/misc/TileInscriber.java#L145): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [TileInscriber.java#L155](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/11f74873f3a2c9ab19daaee3cf6ede3c7ba8f1d2/src/main/java/appeng/tile/misc/TileInscriber.java#L155): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [TileInscriber.java#L184](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/11f74873f3a2c9ab19daaee3cf6ede3c7ba8f1d2/src/main/java/appeng/tile/misc/TileInscriber.java#L184): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by orod-org** [comment]
SonarQube analysis reported 8 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [TileMolecularAssembler.java#L202](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/d57c84ed36d4ac628e00bdbc0cb813b2a9e3291b/src/main/java/appeng/tile/crafting/TileMolecularAssembler.java#L202): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [TileMolecularAssembler.java#L210](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/d57c84ed36d4ac628e00bdbc0cb813b2a9e3291b/src/main/java/appeng/tile/crafting/TileMolecularAssembler.java#L210): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [TileMolecularAssembler.java#L216](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/d57c84ed36d4ac628e00bdbc0cb813b2a9e3291b/src/main/java/appeng/tile/crafting/TileMolecularAssembler.java#L216): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [TileMolecularAssembler.java#L237](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/d57c84ed36d4ac628e00bdbc0cb813b2a9e3291b/src/main/java/appeng/tile/crafting/TileMolecularAssembler.java#L237): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [TileInscriber.java#L135](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/d57c84ed36d4ac628e00bdbc0cb813b2a9e3291b/src/main/java/appeng/tile/misc/TileInscriber.java#L135): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [TileInscriber.java#L145](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/d57c84ed36d4ac628e00bdbc0cb813b2a9e3291b/src/main/java/appeng/tile/misc/TileInscriber.java#L145): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [TileInscriber.java#L155](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/d57c84ed36d4ac628e00bdbc0cb813b2a9e3291b/src/main/java/appeng/tile/misc/TileInscriber.java#L155): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)
1. ![MINOR][MINOR] [TileInscriber.java#L184](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/d57c84ed36d4ac628e00bdbc0cb813b2a9e3291b/src/main/java/appeng/tile/misc/TileInscriber.java#L184): Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](https://sonar.orod.org/coding_rules#rule_key=squid%3AS00100)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by yueh** [comment]
test this please.

**Comment by ridvanonal** [comment]
When we use the inscriber correctly? Next aplha?

**Comment by chooven** [comment]
Hello, we are having a problem in _All the mods 3_ with getting the same processor out of the inscribers no matter what circuit is used.  Will this fix that problem or should I create a new issue?  Thank you

**Comment by fscan** [comment]
Please try with latest alpha (rv5-alpha-2) and open an issue if it is still happening

**Comment by chooven** [comment]
fscan, tried it with ATM3 and alpha 2 works like a champ, i was able to make all three processors.

Thanks

**Pull request merged**
