### PR TITLE
Fix warnings in eclipse

### PR DESCRIPTION
**Pull request by TheJulianJES**
This fixes warnings in eclipse, yes some people are still using eclipse :)
If the review is accepted I will also create a PR for rv2 if wanted.

### CODE REVIEW

**Comment by thatsIch** [comment]
What errors are they fixing?

**Comment by plumpudding** [comment]
Yup I was getting that too. There is an error because the resources are included twice in the Eclipse classpath.

**Comment by thatsIch** [comment]
What does eclipse consider a resource?

**Comment by TheJulianJES** [comment]
http://imgur.com/Fqltju1

**Comment by thatsIch** [comment]
There are no resources? Tell eclipse its drunk!

**Comment by thatsIch** [comment]
nvm its probably about the `Scanner` usage

**Comment by TheJulianJES** [comment]
Also @plumpudding to the double resource issue: http://stackoverflow.com/questions/26755674/importing-project-build-path-contains-duplicate-entry-src-for-project

**Comment by plumpudding** [comment]
My Eclipse even showed an error (not a warning). I can reproduce it if you want.

**Comment by TheJulianJES** [comment]
@plumpudding Yeah, that link fixes the error. This PR fixes warnings I had in my two eclipse instances.

**Comment by thatsIch** [comment]
@TheJulianJES it does not fix them, you just hide them, which is bad. Warnings are a good thing, cause they can detect potential errors and bugs.

**Comment by TheJulianJES** [comment]
@thatsIch I thought they are just issues in a eclipse (1. and 2.) and not in idea.

**Comment by thatsIch** [comment]
Generally its not bad, since this object will be cleaned up anyways after the code block is executed. 
Also here it is applied to a String, so no external resources like files are in use, so it is actually eclipse messing up.

**Comment by TheJulianJES** [comment]
Okay, now I'm messed up...

**Comment by thatsIch** [comment]
I accept the `all` fix, the `resource` is just wrong here, since there are no resources in the first place. But closing the `Scanner` is still a good thing, if you do not want to do it, I can do it.

**Comment by TheJulianJES** [comment]
@thatsIch Is it okay?

**Comment by thatsIch** [comment]
Make the `Scanner` final and you are done :)

**Comment by TheJulianJES** [comment]
I usually make things never final..

**Comment by thatsIch** [comment]
Good practice, prevents you from modifying code without your consent

**Comment by TheJulianJES** [comment]
@thatsIch Should I also pull this to rv2 or is it not necessary?

**Comment by thatsIch** [comment]
please do

**Comment by TheJulianJES** [comment]
Will do tomorrow

**Pull request merged**
