### PR TITLE
Fix Storage Bus internal item tree and item name sorting in terminals.

### LINKED ISSUE #6737: Strange display/sort issue with Storage Bus
### Describe the bug

To put it briefly, the terminal is spastic when displaying items in storage containers connected via Storage Bus.

https://streamable.com/7l446j

In the video, there are no items moving into or out of the system. They're just sitting in barrels. I've tried using different sort types to no avail. 

### How to reproduce the bug

1. Setup a basic AE2 system. I set this up without a controller as I didn't need much, just to view items.
2. Attach external storage. 
3. Pump in a bunch of items. Seems to be worse with unstackables, like armor in this video.

I've replicated this by attaching Occultism storage, Functional Drawers (Armory Cabinet), or Sophisticated Storage (bunch of drawers attached by a controller). For what it's worth, these items are all from Apotheosis. I discovered this while testing loot tables by running the followin command on repeat to test the output. `/loot spawn 393.73 62.69 -150.40 loot minecraft:chests/village/village_armorer`

### Expected behavior

The items should remain in a static sort pattern without moving unless items are coming in or out of the system. 

### Additional details

Cannot replicate with disks. So it seems like it's just the Storage Bus. 

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Forge

### Crash log

n/a

### PR DESCRIPTION
**Pull request by berryh**
Fixes #6737 and #6732.

### CODE REVIEW

**Comment by Technici4n** [comment]
No, outputting the whole NBT to a string is going to be too slow... Another solution will need to be found. Maybe I can have a look tonight.

Also, please submit PRs to the master branch.

**Comment by berryh** [comment]
Fair enough, if you say so. Would this apply to both situations? As in, both to the comparator for the storage map as well as the comparator for item sorting? I've also played with doing it based on tooltip lines (as that's what the player sees so it probably feels the most intuitive) but that probably performs just as poorly then?

**Comment by Technici4n** [comment]
Yeah, in both cases there can be performance issues if 1000s of similar items need to be compared, which is likely to happen in edge cases.

**Comment by Technici4n** [comment]
You can see the fix at #6759, it was a subtle bug.

**Comment by berryh** [comment]
Cool! Also, now more of an FYI then anything: I did some more testing yesterday with the changes (converted to a mixin) in this PR on a server with a fairly large/progressed world and a bunch of non-stacking items in storage buses. Frame-rate on the client-side remains the same as without, but getting items in and out of a terminal and crafting in a crafting terminal gets a bit more sluggish. It's not terrible or unusable, but definitely noticeable. You feel that it takes a little longer to insert or extract an item for example. The server's TPS is slightly affected as well, see the mod view for this Spark report: https://spark.lucko.me/CoPDy611wa

**Comment by berryh** [comment]
Yeah, saw it as well. Don't think it's too bad, but certainly has an impact. I'd expect your fix to perform a lot better.

**Comment by berryh** [comment]
The only thing left is the very odd ordering when using name-based sorting, but I'd say that's not a major problem or priority right now. Also, that does probably need a better performing way then sorting by tooltip lines.

See these tooltips for an example and note the position of the unenchanted Stone Pickaxe.
afbeelding
afbeelding
afbeelding

**Pull request closed without merging**
