### PR TITLE
Updated Readme

### PR DESCRIPTION
**Pull request by yueh**
Added some more details about the translation process.

### CODE REVIEW

**Comment by liach** [comment]
By the way why is this project inactive?

**Comment by KamranMackey** [comment]
@liach It's not inactive. Check the 1.10 branch. They're working on porting the mod to 1.10.

**Comment by liach** [comment]
@KamranMackey Guy it was not active 15 days ago but it is active now.

**Comment by KamranMackey** [comment]
@liach It was active 15 days ago. Check the commit history for the 1.10 branch. And kindly don't call me guy when mentioning my name. It's not really needed lol.

**Comment by shartte** [comment]
@liach The best view I could find to judge activity on a repo is actually the network view:
https://github.com/AppliedEnergistics/Applied-Energistics-2/network

I also sometimes fall into the trap of judging a repo based on its master branch alone (since that's what the commit view will show).

**Pull request merged**
