### PR TITLE
Fixes #1536: Checking for all required BC classes

### LINKED ISSUE #1536: Crash with old BC with old API
Or something along the line,
easy fix is checking all used classes of BC

http://openeye.openmods.info/crashes/4a4712f0f0bba95651ebd887f98659a0

### PR DESCRIPTION
**Pull request by thatsIch**

### CODE REVIEW

**Comment by yueh** [comment]
Missing classes:

* `buildcraft.api.blueprints.IBuilderContext`
* `buildcraft.api.blueprints.SchematicTile`
* `buildcraft.api.blueprints.SchematicBlock`
* `buildcraft.api.transport.IPipeTile.PipeType`

**Comment by thatsIch** [comment]
Added them

**Comment by TheJulianJES** [comment]
@thatsIch Can we also get that for rv2?

**Comment by thatsIch** [comment]
currently building it

**Comment by TheJulianJES** [comment]
@thatsIch Ohh, didn't know this was merged 1 minute ago, sorry..

**Pull request merged**
