### PR TITLE
Use action bar for feedback messages

### PR DESCRIPTION
**Pull request by jpenilla**
Implements #6864

### CODE REVIEW

**Review by Technici4n — CHANGES_REQUESTED** [review]
Hmmm, is it not possible to call `player.displayClientMessage(component, true)` for action bar messages?

**Comment by Technici4n** [comment]
Just noticed, is it intended that you're PR'ing to `fabric/1.19.2` and not `master`?

**Comment by jpenilla** [comment]
> Hmmm, is it not possible to call `player.displayClientMessage(component, true)` for action bar messages?

That should work, I just missed it because I looked at `ClientboundSetActionBarTextPacket` and worked backward. Do you want me to call `displayClientMessage` with true at all call sites, or keep the util method to make things more clear without checking what the `true` param means?

> Just noticed, is it intended that you're PR'ing to `fabric/1.19.2` and not `master`?

I had that branch checked out locally and there were conflicts with master :sweat_smile: will rebase shortly

**Comment by Technici4n** [comment]
I think it's best to inline the helper method, otherwise we might have inconsistent code at some point (using the method vs the bool parameter)

**Pull request merged**
